quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=onechaq
quarkus.datasource.password=onechaq
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/onechaq
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://onechaq-postgres:5432/onechaq
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
%prod.kafka.bootstrap.servers=kafka:9092
mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=chat-messages
mp.messaging.outgoing.messages-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.messages-in.connector=smallrye-kafka
mp.messaging.incoming.messages-in.topic=chat-messages
mp.messaging.incoming.messages-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.auto.offset.reset=latest
mp.messaging.incoming.messages-in.group.id=${chat.group.id:onechaq-dev}
%prod.quarkus.redis.hosts=redis://redis:6379
